### ISSUE TITLE
115 Lights are created

### ISSUE THREAD

**Issue by ZomuHD** [HexoCraft/AddLight#11]
Hello
I have a problem I have installed on my server AddLight and lamps. Only now comes a message [AddLight] 115 Lights are created. How to increase the number? In the config I have set to 2000 but it does not work.

I'm sorry for my bad english I have that translated from German to English by the Google translator

**Comment by hexosse** [comment]
Do you use the connected block mode ?

**Comment by ZomuHD** [comment]
No i write /addlight enable

**Comment by hexosse** [comment]
Is this still an issue?
