### ISSUE TITLE
Add lights without requiring a player?

### ISSUE THREAD

**Issue by Cryptite** [HexoCraft/AddLight#13]
The way we intend to use this plugin, it'd be superb if we could call create/removeLight without requiring a Player object. This should be fairly trivial, but right now calling with a null player will throw an exception due to the Permissions checks.

**Comment by hexosse** [comment]
Do you want to create lights with the API or do you want to create/remove lights from the console?

**Comment by Cryptite** [comment]
With the API.

**Comment by hexosse** [comment]
ok so just use : 

``` java
  Lights.createLight(final Location location, final int light)
  Lights.createLight(final List<Location> locations, final int light)
```
and

``` java
  Lights.removeLight(final Location location)
  Lights.removeLight(final List<Location> locations)
```

located in package : com.github.hexocraftapi.lights

You might just want to use my light API : https://github.com/HexoCraftApi/Lights
so you don't need to use AddLight plugin.

If this is the case, you can add the API to your plugin

``` xml
        ...
        <repository>
            <id>hexosse-repo</id>
            <url>https://raw.github.com/hexosse/maven-repo/master/</url>
		</repository>
        ...
````

``` xml
        ...
        <dependency>
            <groupId>com.github.hexocraftapi</groupId>
            <artifactId>lights</artifactId>
            <version>[1.0.0, )</version>
        </dependency>
        ...
````

**Comment by Cryptite** [comment]
Ah. That works. Didn't know it'd updated to 1.12 so I think I was having some issues with it previously. Thanks!
