### ISSUE TITLE
Commands don't work.

### ISSUE THREAD

**Issue by braingame49** [HexoCraft/AddLight#14]
Every command in the latest build (4.2.0) doesn't work.
Maybe because my server is Paper 1104.

If you can fix this issue, then I would really like it.

- braingame49

p.s. log: https://pastebin.com/UbSGs9tr

**Comment by hexosse** [comment]
Hi,

I just tried with paper-1104 and I don't have such issue.
However, when I look at your log, it seems that the problem comes from PerWorldPlugins.

Try again without this plugin and let me know.

**Comment by hexosse** [comment]
I'm closing this issue as you did not answer me !
