### ISSUE TITLE
Light sources being removed

### ISSUE THREAD

**Issue by LogGits** [HexoCraft/AddLight#16]
I have been noticing light sources have been disappearing. Any idea why light sources could be removed upon restart?

**Comment by DoreK333** [comment]
At me, the light source started to disappear after re-entering the server :(

**Comment by LogGits** [comment]
Yeah im having the same issue.

**Comment by hexosse** [comment]
That's actually a problem whenever you have ```random-light-updates: true``` in your spigot.yml.
I'm trying to find a workaround with no luck for the moment.

In fact, I could store any lights position and restore them using the same process as spigot does with random lights update. However, I think this is not a good solution as I don't want to store any lights positions.

Working on it, stay tuned ...

**Comment by LogGits** [comment]
@hexosse Just a heads up my random-light-updates is set to false and i still get this issue.

**Comment by DoreK333** [comment]
@LogGits me too ;)

**Comment by hexosse** [comment]
@LogGits @DoreK333 Are you are using FastAsyncWorldedit ?

**Comment by DoreK333** [comment]
No.

**Comment by LogGits** [comment]
@hexosse yes I am, and I am also using PaperSpigot

**Comment by LogGits** [comment]
@DoreK333 Are you using PaperSpigot aswell?

**Comment by DoreK333** [comment]
yes ;)

**Comment by Cryptite** [comment]
As I understand it, Paper recently removed random-light-updates as a thing. They will always update lightmaps now. Will probably need to look into another way around it.

**Comment by DoreK333** [comment]
Can I find out when it will be fixed?

**Comment by Cryptite** [comment]
@hexosse Any luck on this?

**Comment by hexosse** [comment]
Not yet.
Working on it

**Comment by LogGits** [comment]
@hexosse is there an event that you can hook into like a LightingUpdateEvent or something like that? If not maybe he paperspigot team could implement such a feature upon request?

**Comment by hexosse** [comment]
There is no message like that.
Lights depend on the mechanics of each block type.
AddLights, change this data but it seems to be reset some way?

**Comment by LogGits** [comment]
@hexosse could this potentially fix this issue?
https://ci.destroystokyo.com/job/PaperSpigot/1275/changes
It is a recent update.

**Comment by DoreK333** [comment]
I checked and now everything works as it should
