### ISSUE TITLE
Spigot 1.12.2 Silent Errors?

### ISSUE THREAD

**Issue by Piefanatic555** [HexoCraft/AddLight#17]
First time trying out the plugin as LightSource was defunct, and it's acting rather strange.

Absolutely no errors in console, and also absolutely no mention that it attempted to load, yet the plugin default configs are made on server start. While on the server, it shows fine in the plugin list but all commands respond as if the plugin doesn't exist. Any tips?

FYI, it looked like there may be typos in the default configs and attempts to correct them are reverted on a server reboot.

**Comment by Piefanatic555** [comment]
OK, I tried adding the previous dependency LightAPI to see if anything showed up and I got this in console:

03.12 20:32:47 [Server] INFO Enabling AddLight v4.2.0 03.12 20:32:47 [Server] WARN Enabled plugin with unregistered PluginClassLoader AddLight v4.2.0 03.12 20:32:47 [Server] WARN java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='knownCommands', types=[]}] in class class us.Myles.PWP.FakeSimpleCommandMap 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:174) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:27) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:76) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.reflection.resolver.FieldResolver.resolve(FieldResolver.java:73) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.reflection.util.FieldUtil.getField(FieldUtil.java:42) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.reflection.util.FieldUtil.getField(FieldUtil.java:74) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.command.CommandRegistration.getKnownCommands(CommandRegistration.java:100) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.command.CommandRegistration.getKnownCommands(CommandRegistration.java:94) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.command.CommandRegistration.isRegisteredCommand(CommandRegistration.java:80) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.command.CommandRegistration.registerCommand(CommandRegistration.java:39) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.api.plugin.Plugin.registerCommands(Plugin.java:71) 03.12 20:32:47 [Server] WARN at com.github.hexocraft.addlight.AddLightPlugin.onEnable(AddLightPlugin.java:68) 03.12 20:32:47 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) 03.12 20:32:47 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)

**Comment by hexosse** [comment]
Hi, this is not an AddLight error.
This is due to PerWorldPlugin not handling auto register commands.
