### ISSUE TITLE
Strange Height Limitation

### ISSUE THREAD

**Issue by Adam759** [HexoCraft/AddLight#18]
Recently when working on a build, I went to use AddLight and it seems there is a hard height limit for it, 128 blocks. AddLight will not add any light above this threshold. Any reason why? Is this by design or is there something else going on? Thanks!

**Comment by hexosse** [comment]
This is strange as I don't have any limitations on hight.
Could you give me more detail :
- bukit/spigot version
- plugin version

**Comment by hexosse** [comment]
Do you have any errors in your console log?
Did you you try without other plugins ?

**Comment by Selebrator** [comment]
I can confirm.
Java Version: `1.8.0_141 64bit`
Cleint Version: `1.12.2/vanilla`
Spigot version: `This server is running CraftBukkit version git-Spigot-4bd94dc-f4ca180 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`
Plugin version: `AddLight v4.2.0`
No other plugins used.
[latest.log](https://github.com/HexoCraft/AddLight/files/1721019/latest.log)

At `y=64` AddLight light behaved as expected. 
At `y>128` AddLight light did not appear. Torch light behaved as expected.
At `y=128` The lower half of the block lights up and it can be made to light up completely (not shure what exact actions make that happen).
AddLight did not appear anywhere in the log except on enable, command and disable. No exceptions thrown.

**Comment by hexosse** [comment]
I'm working on it, but the light mechanism is a bit tricky.

**Comment by hexosse** [comment]
Just found a solution.
Update to AddLight 4.2.1
