### ISSUE TITLE
Debug info on open hand?

### ISSUE THREAD

**Issue by DeusNinja** [HexoCraft/AddLight#2]
I'm getting this http://prntscr.com/de6a57 everytime something is clicked with an open hand, not sure if it's related to addlight, I saw no config option for a info tool about light level. Please let me know how I can disable this.

**Comment by DeusNinja** [comment]
When addlight is toggled on, the plugin enables light inspector/block inspector tool to open hand, not only for the person who is using the plugin, but for every user, even ones who do not have any addlight permissions. Toggling addlight off disabled the inspection tool for everyone.

**Comment by hexosse** [comment]
That's the debug info I used while doing my light API.
I'm going to add a permission for this, as I found it useful.
I'll release a new version just after.

**Comment by DeusNinja** [comment]
Could you please make the debug info not default for op?

**Comment by hexosse** [comment]
Done it in 4.0.4
