### ISSUE TITLE
Working in some regions but not others

### ISSUE THREAD

**Issue by MuseumTester** [HexoCraft/AddLight#22]
I'm having trouble with the plugins. It's enabled, and I'm able to add light in some regions, but not others. I thought it might be a world guard issue, but when I look at the flags on things that work and things that don't, I can't figure out a common denominator.  Demonstrated here: https://youtu.be/eDbvHXPPMtU

**Comment by hexosse** [comment]
I actually have an issue with blocks above 128.
Is it the case?

**Comment by MuseumTester** [comment]
Oh, that might be it! It started happening again with a build on a mountain. The blocks are clearly registering as light sources, because snow is melting, but no light.

**Comment by hexosse** [comment]
Just found a solution.
Update to AddLight 4.2.1
