### ISSUE TITLE
can not add or remove lights.. 1.13.1

### ISSUE THREAD

**Issue by WHiZSTA** [HexoCraft/AddLight#28]
01.09 16:22:50 [Server] ERROR Could not pass event PlayerInteractEvent to AddLight v4.2.2 01.09 16:22:50 [Server] INFO java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.WorldEditPlugin.getSelection(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/bukkit/selections/Selection; 01.09 16:22:50 [Server] INFO at com.github.hexocraft.addlight.integrations.WorldEditHooker.isLocationInSelection(WorldEditHooker.java:81) ~[?:?] 01.09 16:22:50 [Server] INFO at com.github.hexocraft.addlight.LightsApi.removeLight(LightsApi.java:207) ~[?:?] 01.09 16:22:50 [Server] INFO at

**Comment by Pomdre** [comment]
same with me

**Comment by hexosse** [comment]
Could you tell me which version of WorldEdit you are using ?

**Comment by Pomdre** [comment]
I am using http://builds.enginehub.org/job/worldedit/10385

**Comment by WHiZSTA** [comment]
Yeah that's what I'm using too.. hope it's an easy fix as I really need this plugins ability to help make my new spawn..

**Comment by hexosse** [comment]
This is solved from 4.3.0
