### ISSUE TITLE
Latest WorldEdit 7 compatibility

### ISSUE THREAD

**Issue by DynamicThijs** [HexoCraft/AddLight#29]
Hi,

Your plugin doesn't seem to work with the latest builds of WorldEdit 7.0.0.
Here's the error: https://pastebin.com/NE0ZghEQ

Can you make it compatible?

Thanks in advance!

**Comment by DynamicThijs** [comment]
It's the vector update which makes it incompatible.

**Comment by hexosse** [comment]
Just released 4.3.2: https://dev.bukkit.org/projects/addlight/files/2639562

Just wait a moment for Bukkit to approve the file.

**Comment by Geitenijs** [comment]
Thanks!
