### ISSUE TITLE
LOVE THE PLUGIN - But Doesn't Work With 1.12

### ISSUE THREAD

**Issue by woohoowebs** [HexoCraft/AddLight#7]
Please add support for Minecraft 1.12. Sending good vibes your way! :+1:

**Comment by hexosse** [comment]
Just found the problem.
I try to find a workaround and I'll post a new release

**Comment by pinkphoenix1990** [comment]
Thank you for all your work on this! I was crushed when I realized that updating my server to 1.12 had stopped this plugin from working!

**Comment by hexosse** [comment]
Version 4.1.5 solve the problem.

**Comment by woohoowebs** [comment]
Absolutely did the trick and such a fast fix. Thanks so much!!
