### ISSUE TITLE
1.12 Compatibility ?

### ISSUE THREAD

**Issue by M4rtyn4** [HexoCraft/AddLight#8]
Latest Spigot and Bukkit:
Error occurred while enabling AddLight v4.1.5 (Is it up to date?)

:(

**Comment by hexosse** [comment]
I just recompiled the latest spigot 1.12 and I don't have this problem.
Can you send me the full log?

**Comment by M4rtyn4** [comment]
Hello
Did you find out what was causing version incompatibility?
Im really looking forward to use your plugin in my server.
M4rtyn4

**Comment by hexosse** [comment]
Do you still have the problem?

**Comment by hexosse** [comment]
No answer, so I close this issue
