### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by ThiagoPalmeira** [HexoCraft/AddLight#9]
I can not put a player to use the command alone with CMD please help me

**Comment by hexosse** [comment]
I'm not sure to understand what you mean !!!

If you want a player to be able to use AddLight, then give him the AddLight.user permission.
You can also give him one of those permissions: AddLight.worldedit, AddLight.connected, AddLight.intensity

Then your player just have to use a glowstone dust to add lights all around

**Comment by ThiagoPalmeira** [comment]
But where to put the permissions

**Comment by ThiagoPalmeira** [comment]
But where to put the permissions

**Comment by hexosse** [comment]
You need a permission plugin like PermissionEx, GroupManager ...
Or to be OP

**Comment by ThiagoPalmeira** [comment]
I did so the / pex group AddLight.admin create and I put it and it is not working

**Comment by ThiagoPalmeira** [comment]
please answer me

**Comment by hexosse** [comment]
Create a group :
`/pex group AddLightUser create`

Add permissions to the group : 
`/pex group AddLightUser add AddLight.user`
`/pex group AddLightUser add AddLight.worldedit`
`/pex group AddLightUser add AddLight.connected`
`/pex group AddLightUser add AddLight.intensiy`

Then add a user into the group :
`/pex user hexosse group add AddLightUser`

**Comment by ThiagoPalmeira** [comment]
Please be patient. 1.8
